# -*- coding: utf-8 -*-
"""dictexcfinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQmHc8qfITBbyoD9ZNNqzX6YKZ998pac
"""

#1

a = []
b = []

for i in range(10):
  a.append(int(input("enter number")))

print(a)

for i in range(0, 10, 2):
  b.append(a[i + 1])
  b.append(a[i])

print(b)

#2 

a = []
wrong = []

for i in range(10):
  a.append(int(input("enter number")))
print(a)

for i in range(10):
  if (i % 2 == 0): # zogi spot
    if (a[i] % 2 != 0): # wrong
      wrong.append(a[i])

  else: #ezogi spot
    if (a[i] % 2 == 0): 
      wrong.append(a[i])

print(f'the numbers in the wrong spot: {wrong}')

#3

longest = ''
shortest = ''
a = ''
b = ''

s = input("enter string: ")
l = list(s.split(' '))
print(l)

longest = max(l)
shortest = min(l)

for i in range(len(longest)):
  a += '*'

for i in range(len(shortest)):
  b += '+'

l[l.index(longest)] = a
l[l.index(shortest)] = b
print(l)

#4

shop={'onion':5, 'milk':10, 'Bread':7,'tea':9,'pita':3}
print(shop)
prices = []
new_shop = {}

for i in shop.values():
  prices.append(i)
prices.sort(reverse=True)
prices = prices[:3]

for i in prices:
  for key in shop.keys():
    if (shop[key] == i):
      new_shop.update({key:i})
print(new_shop)

#5

l = [(10, 20, 40), (40, 50 ,60), (70, 80, 90)]
new_l = []
t_list = []

for i in range(len(l)):
  t_list = list(l[i])
  t_list.append(sum(l[i]))
  new_l.append(tuple(t_list))

print(new_l)

#1 dict hagai


v = [1, 3, 5, 6, 9]
k = ['itamar', 'gadi', 'ofer', 'ofri', 'greg']
d = {}

for i in range(len(k)):
  temp = {k[i]:v[i]}
  d.update(temp)

print(d)

#2 dict hagai

import random

d = {'onion':5, 'milk':10, 'Bread':7,'tea':9,'pita':3}
r = random.choice(list(d))

print(d)
d.pop(r, "error")

print(d)

#3 dict hagai

import operator

d = {'c':3, 'a':5, 'b':6, 'e':3, 'd':1}
sk = []
k = []
sv = []
v =[]
sortByKey = {}
sortByVal = {}

for key in d.keys():
  k.append(key)

for val in d.values():
  v.append(val)

thisdictKeys = sorted(d.items())

thisdictVals = sorted(d.items(), key = operator.itemgetter(1))

  
print(thisdictKeys)
print(thisdictVals)

#hagai final test 2

import math
import random

list1 = []

def transfer(list1):
  x = []
  y = []

  for i in list1:
    if (i > 0 ):
      x.append(math.sqrt(i))
    elif (i < 0):
      y.append(abs(i))

  return x,y,list1

for i in range(10):
  list1.append(random.randint(-5,5))

print(transfer(list1))

#1

d = {'a':2, 'b':8, 'c':4, 'd':9, 'e':3}
flag = True
num = int(input("Enter number: "))

for i in d.values():
  if (i == num):
    flag = False

if (flag == True):
  print(f'The number: {num} is not in the array :(')
else:
  print(f'The number: {num} is in the array :)')

#2

d = {'1':100, '2':101, '3':102, '4':103, '5':104, '6':105, '7':106, '8':107, '9':108, '10':109}

for i in d.items():
  print(i)

#3

d = {1:100, 2:101, 3:102, 4:103, 5:104}
v = []

for i in d.values():
  v.append(i)

print(min(d.values()))
print(sum(v))

#4

k = ['a', 'b', 'c', 'd', 'e']
v = [100, 200, 300, 400, 500]
a = {}

for i in range(len(k)):
  a.update({k[i]: v[i]})

print(a)

#5

import random

d = {'1':100, '2':101, '3':102, '4':103, '5':104, '6':105, '7':106, '8':107, '9':108, '10':109}

r = random.choice(list(d))

print(d)
print(r)
d.pop(r)
print(d)

#6

d = {'c': 100, 'b': 40, 'd':50, 'e':90, 'a':200}
k = sorted(d.items(), key=lambda x: x[0])
v = sorted(k, key=lambda x: x[1])

print(k)
print(v)

#7
list1 = ['gal', 90, 'tal', 100, 'ran', 85, 'sigal', 40]

names = []
grades = []
fin = []

for i in range(0, 8, 2):
  names.append(list1[i])
  grades.append(list1[i+1])

print(grades,names)

for i in range(len(names)):
  namedict = {}
  namedict['Name'] = names[i]
  namedict['Grade'] = grades[i]
  fin.append(namedict)

print(fin)

#8

sum = 0

prices = {}
prices["banana"] = 4
prices["apple"] = 2
prices["orange"] = 1.5
prices["pear"] = 3

stock = {}
stock["banana"] = 6
stock["apple"] = 0
stock["orange"] = 32
stock["pear"] = 15

print(prices)
print(stock)

for i in stock:
  sum += stock[i] * prices[i]

print(sum)

#9

empList = [
    {'name' : 'Ran', 'salery' : 7500},
    {'name' : 'Dan', 'salery' : 8000},
    {'name' : 'Gal', 'salery' : 9500},
    {'name' : 'Sigal', 'salery' : 11500},
    {'name' : 'Gad', 'salery' : 6000},   
]

for i in empList:
  i['salery'] *= 1.1

print(empList)

# hagai final test question 1 *hard****
import random


def school_classes(school):
  sum = 0

# a
  school['Yg11'] += 2
  school['Yg1'] -= 3

# b
  smallest = list(sorted(school.values()))
  print(smallest[0])

  for item in school:
    if int(school[item]) == smallest[0]:
      school.pop(item)
      break

  sub = float(smallest[0]) / 3
  for item in school:
    school[item] += int(sub)

# c
  biggest = list(sorted(school.values()))
  print(biggest[2])
  subc = float(biggest[2]) / 2
  school.update({'Yg4': int(subc)})

  for item in school:
    if int(school[item]) == biggest[2]:
      print(item)
      school[item] -= int(subc)
# d
  for item in school:
    sum += school[item]
  print(sum)

# e
  print(sorted(school.items(), key=lambda x: x[1]))

  return school

school = {'Yg11': random.randint(20, 30), 'Yg9': random.randint(20, 30), 'Yg8': random.randint(20, 30), 'Yg1': random.randint(20, 30),}
print(school)
print(school_classes(school))

# matala 13 files 1

f = open ("1.txt", "r")
print(f.read())
f.close()

# matala 13 files 2

num = int(input("Enter numver: "))

f = open ("1.txt", 'r')
for i in range(num):
  print(f.readline())

f.close()

# matala 13 files 3

s = input("Enter a word: ")

f = open ("1.txt", "r")

counter = (f.read().count(s))

f.close()

print(counter)

# matala 13 files 4
l1 = []
l2 = []

f = open ("1.txt", 'r')
for i in f:
  l1.append(i)
f.close()

print(l)
############################## another option

f = open ("1.txt", 'r')

print(f.readlines())

f.close()

# matala 13 files 5 - same as 3

s = input("Enter a string: ")
counetr = 0

f = open ("1.txt", 'r')
counter = (f.read().count(s))
  
f.close()

print(counter)

# matala 13 files 6

wordcount = 0
tavcounter = 0

f = open ("1.txt", 'r')
for i in f:
  templine = i.split(' ')
  for j in templine:
    if len(j) == 1:
      tavcounter += 1
    else:
      wordcount += 1
f.close()

print(f'Word counter: {wordcount}, Tav counter: {tavcounter}')

# matala 13 files 7

s = input("Enter a string: ")

f = open("1.txt", 'a')
f.write('\n')
f.write(s)
f.close()


f = open("1.txt", 'r')
print(f.read())
f.close()

# matala 13 files 8

n = int(input("Enter a number: "))
l = []

f = open ("1.txt", 'r')
for i in f:
  l.append(i)

for j in range(n, len(l)):
  print(l[j])
f.close()

# matala 13 files 9

l = input("Enter a string: ").split(' ')
print(l)
f = open ("1.txt", 'a')
f.write("\n")
for word in l:
  f.write(word)
  f.write(" ")
f.close()

f = open ("1.txt", 'r')
print(f.read())
f.close()

# matala 13 files 10

l1 = []

f1 = open ("1.txt", 'r')
for i in f1:
  l1.append(i)
f1.close()

f2 = open ("2.txt", 'w')
for i in l1:
  #print("\n")
  f2.write(i)
f2.close()

f3 = open ("2.txt", 'r')
print(f3.read())
f3.close()

# tirgul files hagai 1

f = open ("1.txt", 'r')
print(f.readlines())
f.close()

# tirgul files hagai 2

cnt = 0
f = open('1.txt', 'r')
st = input("Enter A Word: ")
for line in f:
  lst = line.split(' ')
  cnt += lst.count(st)
print(cnt)
f.close()

# tirgul files hagai 4

shop = {}
templist = []

f = open ("2.txt", 'r')
for i in f:
  templist = i.rstrip('\n').split(' ')
  shop[templist[0]] = [templist[1], templist[2]]
f.close()

print(shop)

# tirgul files hagai 5

dct = {'Apple' :  5, 'Tomato' : 10,'Banana' : 3,'Potato' : 4}

f = open ("2.txt", 'w')
for i in dct.items():
  f.write(str(i))
  f.write("\n")
f.close()

f2 = open ("2.txt", 'r')
print(f2.read())
f2.close

# tirgul files hagai 6

templist = []

f = open ("1.txt", 'r')
for i in f:
  templist = i.split(' ')
  for j in templist:
    print(j)
f.close()

# tirgul files hagai 7
n = int(input("Enter a number: "))

f = open ("1.txt", 'r')
for i in range(n):
  print(f.readline())
f.close()

# tirgul files hagai 8

s = input("Enter string: ")

f = open ("1.txt", 'a')
f.write("\n")
f.write(s)
f.close()

f = open ("1.txt", 'r')
print(f.read())
f.close()

# tirgul files hagai 12

count = 0
listtemp = []

f = open ("1.txt", 'r')
for i in f:
  listtemp = i.split(' ')
  count += len(listtemp)
f.close()

print(count)

# hagai files q test ******cool*****

l1 = []
l2 = []
l3 = []

f1 = open ("1.txt", 'r')
for i in f1:
  l1.append(i.rstrip())
f1.close()
print(l1)

f2 = open ("2.txt", 'r')
for i in f2:
  l2.append(i.rstrip())
f2.close()
print(l2)

for j in range(len(l1)):
  l3.append(l1[j]+ " " + l2[j])
print(l3)

f3 = open ("3.txt", 'w')
for i in l3:
  f3.write(i)
  f3.write("\n")
f3.close()

f3 = open ("3.txt", 'r')
print(f3.read())
f3.close()

# matrix 1

import random

n = 4 #rows
m = 3 #colums
a = []

for i in range(n):
  b = []
  for j in range(m):
    b.append(random.randint(1, 10))
  a.append(b)

print(a)

for i in a:
  print(i)

# matrix 2

import random

n = 4 #rows
m = 3 #colums
a = []
maxl = []
minl = []

for i in range(n):
  b = []
  for j in range(m):
    b.append(random.randint(1, 10))
  maxl.append(max(b))
  minl.append(min(b))
  a.append(b)

print(a)
print(f'The max value is: {max(maxl)}, The min value is: {min(minl)}')

# matrix 3

n = 4
m = 3
a = []
sumr = 0
sumc = 0

for i in  range(n):
  b = []
  for j in range(m):
    b.append(random.randint(1, 10))
    sumr += b[j]
  b.append(sumr)
  sumr = 0
  a.append(b)

for i in a:
  print(i)

sumcol0 = 0
sumcol1 = 0
sumcol2 = 0

for i in range(n):
  sumcol0 += a[i][0]
  sumcol1 += a[i][1]
  sumcol2 += a[i][2]
print(sumcol0,sumcol1,sumcol2)

# matrix 4

n = 4
m = 3
a = []

for i in range(n):
  b = []
  for j in range(m):
    b.append(random.randint(1, 10))
  a.append(sorted(b, reverse=True))

for i in a:
  print(i)

# hagai list and matrix 8

l = []

for i in range(10):
  l.append(int(input("Enter num: ")))

for i in range(len(l)):
  if l[i] < 0:
    l[i] = -1
  elif l[i] > 0:
    l[i] = 1
  else:
    l[i] = 0
print(l)

# hagai list and matrix 9

lst = [1, 2, -5, 7, -100, 0, 1]
pc = 0
nc = 0
zc = 0

for i in lst:
  if i == 0:
    zc += 1
  elif i > 0:
    pc += 1
  else:
    nc += 1

print(f'pc: {pc}, nc: {nc}, zc: {zc}')

# hagai list and matrix 10

import random

lst = []

for i in range(10):
  lst.append(random.randint(1, 100))
print(lst)

for i in lst:
  if (35 < i < 65):
    print(i)
    lst.remove(i)
print(lst)

# hagai list and matrix 11

import random

lst = []
x = []
y = []

for i in range(10):
  lst.append(random.randint(-5, 5))
print(lst)

z = lst

for i in lst:

  if i > 0:
    x.append(i)
    
   
  elif i < 0:
    y.append(i)
    

print(x)
print(y)
print(z)

# hagai list and matrix 12

lst = []

for i in range(20):
  lst.append(random.randint(1, 20))
print(lst) 

lst = sorted(lst)
print(lst)

for i in range(19):
  if lst[i] == lst[i + 1]:
    flag = True

if flag == True:
  print("There are dubles")
else:
  print("Every number appears only once in the list")

# hagai list and matrix 13

lst = []
single = []

for i in range(20):
  lst.append(random.randint(1, 20))
print(lst) 

lst = sorted(lst)
print(lst)

for i in range(19):
  if lst[i] == lst[i + 1] or lst[i] == lst[i - 1]:
    flag = True
  else:
    single.append(lst[i])

if flag == True:
  print("There are dubles")
else:
  print("Every number appears only once in the list")

print(single)

# hagai list and matrix 14

import random

n =6
m = 7
a = []
lx = []
temp = []

num = int(input("Enter num in range 1 to 10: "))

for i in range(n):
  b = []
  for j in range(m):
    x = random.randint(1, 10)
    b.append(x)
    if x == num:
      temp = [i, j]
      lx.append(temp)
  a.append(b)

print(a)
print(num)
print(lx)

# hagai list and matrix 15